//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaphetyToDDL.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaphetyToDDL.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;invoice docInstanceId=&quot;5a7edb94-530d-3a5f-b979-d8849c3ec521&quot; documentCorrelationId=&quot;521af6a2-0032-48a0-b92c-7c9d140aea65&quot; docTypeId=&quot;1&quot;&gt;
        /// &lt;senderSoftwareCertificationNumber&gt;xxxx&lt;/senderSoftwareCertificationNumber&gt;
        /// &lt;senderSoftwareDocumentSignatureHash&gt;xxxx&lt;/senderSoftwareDocumentSignatureHash&gt;
        /// &lt;currencyISOCode&gt;EUR&lt;/currencyISOCode&gt;
        /// &lt;documentNumber&gt;FT01/simples&lt;/documentNumber&gt;
        /// &lt;documentDates&gt;
        ///  &lt;documentDate&gt;2019-01-16&lt;/documentDate&gt;
        ///  &lt;dueDate&gt;2019-02-16&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string saphetySampleFile1 {
            get {
                return ResourceManager.GetString("saphetySampleFile1", resourceCulture);
            }
        }
    }
}
