//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaphetyToDDL.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaphetyToDDL.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;TransDocType&quot;:1,
        ///   &quot;TransBehavior&quot;:1,
        ///   &quot;TransactionGuid&quot;:&quot;9C2DE3B6101F8347B8FB12B5B4234AE5&quot;,
        ///   &quot;TempTransIndex&quot;:0.0,
        ///   &quot;CreateDate&quot;:&quot;2025-10-13T00:00:00&quot;,
        ///   &quot;CreateTime&quot;:&quot;1899-12-30T12:49:40&quot;,
        ///   &quot;DeferredPaymentDate&quot;:&quot;2025-10-14T00:00:00&quot;,
        ///   &quot;ActualDeliveryDate&quot;:&quot;2025-10-13T00:00:00&quot;,
        ///   &quot;ContractReferenceNumber&quot;:&quot;8084103759&quot;,
        ///   &quot;DefaultWarehouse&quot;:2005,
        ///   &quot;PartyAddressID&quot;:0,
        ///   &quot;PartyAddressLine1&quot;:&quot;Morada nº 1 do Cliente nº 102021&quot;,
        ///   &quot;PartyAddressLine2&quot;:&quot;&quot;,
        ///   &quot;PartyPostalCod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ddlSampleString {
            get {
                return ResourceManager.GetString("ddlSampleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;TransDocType&quot;:1,
        ///   &quot;TransBehavior&quot;:1,
        ///   &quot;TransactionGuid&quot;:&quot;B7B9913F92CA1543A72270FF00F261F6&quot;,
        ///   &quot;TempTransIndex&quot;:0.0,
        ///   &quot;CreateDate&quot;:&quot;2025-10-13T00:00:00&quot;,
        ///   &quot;CreateTime&quot;:&quot;1899-12-30T15:17:54&quot;,
        ///   &quot;DeferredPaymentDate&quot;:&quot;2025-10-14T00:00:00&quot;,
        ///   &quot;ActualDeliveryDate&quot;:&quot;2025-10-13T00:00:00&quot;,
        ///   &quot;ContractReferenceNumber&quot;:&quot;8084018270&quot;,
        ///   &quot;DefaultWarehouse&quot;:2005,
        ///   &quot;PartyAddressID&quot;:0,
        ///   &quot;PartyAddressLine1&quot;:&quot;Morada nº 1 do Cliente nº 102021&quot;,
        ///   &quot;PartyAddressLine2&quot;:&quot;&quot;,
        ///   &quot;PartyPostalCod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dllSampleString2 {
            get {
                return ResourceManager.GetString("dllSampleString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;invoice docInstanceId=&quot;5a7edb94-530d-3a5f-b979-d8849c3ec521&quot; documentCorrelationId=&quot;521af6a2-0032-48a0-b92c-7c9d140aea65&quot; docTypeId=&quot;1&quot;&gt;
        /// &lt;senderSoftwareCertificationNumber&gt;xxxx&lt;/senderSoftwareCertificationNumber&gt;
        /// &lt;senderSoftwareDocumentSignatureHash&gt;xxxx&lt;/senderSoftwareDocumentSignatureHash&gt;
        /// &lt;currencyISOCode&gt;EUR&lt;/currencyISOCode&gt;
        /// &lt;documentNumber&gt;FT01/simples&lt;/documentNumber&gt;
        /// &lt;documentDates&gt;
        ///  &lt;documentDate&gt;2019-01-16&lt;/documentDate&gt;
        ///  &lt;dueDate&gt;2019-02-16&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string saphetySampleFile1 {
            get {
                return ResourceManager.GetString("saphetySampleFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;order xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; creationDateTime=&quot;2025-07-22 00:00:00&quot; lastUpdateDate=&quot;2025-07-22 00:00:00&quot; docTypeId=&quot;2&quot; documentCorrelationId=&quot;12340722224102.34a0b2ef-6d79-4556-b283-5529e6040a12&quot;&gt;
        ///  &lt;currencyISOCode&gt;EUR&lt;/currencyISOCode&gt;
        ///  &lt;documentNumber&gt;ENC-123456789&lt;/documentNumber&gt;
        ///  &lt;documentDates&gt;
        ///    &lt;documentDate&gt;2025-07-11&lt;/documentDate&gt;
        ///    &lt;deliveryDate&gt;2025-07-18&lt;/deliveryDate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string saphetySampleFile2Order {
            get {
                return ResourceManager.GetString("saphetySampleFile2Order", resourceCulture);
            }
        }
    }
}
